学習・推論・ノートブック実行時のスクリプト修正

diff --git a/web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/notebook_scripts.yaml b/web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/notebook_scripts.yaml
--- a/web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/notebook_scripts.yaml
+++ b/web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/notebook_scripts.yaml
@@ -14,10 +14,23 @@ data:
     
     if [ -n "$DATASET_ID" ]; then
         echo "------------------------- [KAMONOHASHI Prepare] deploy dataset $DATASET_ID into /kqi/input . -------------------------"
-        kqi dataset download-files -d /kqi/input $DATASET_ID && kqi dataset get -d /kqi/input/meta.json $DATASET_ID
+        kqi dataset get -d /kqi/input/meta.json $DATASET_ID && kqi dataset list-path-pairs $DATASET_ID >/kqi/tmp/datapairs.txt
         if [ $? -ne 0 ]; then
-            echo "dataset download-files failed"
+            echo "dataset get failed"
         fi
+        # default: create symlink to raw-data, $LOCAL_DATASET = True : copy raw-data to local
+        prepare_cmd='ln -s "/kqi/raw/${stored_path}" "/kqi/input/${file_path}"'
+        if [ ${LOCAL_DATASET} = "True" ]; then
+            prepare_cmd='cp "/kqi/raw/${stored_path}" "/kqi/input/${file_path}"'
+        fi
+        while read file_path stored_path
+        do
+            mkdir -p "/kqi/input/$(dirname ${file_path})" && eval ${prepare_cmd}
+        if [ $? -ne 0 ]; then
+            echo "create dataset failed"
+            exit 0
+        fi
+        done </kqi/tmp/datapairs.txt
     fi
   main: |
     if which pip3 > /dev/null 2>&1; then
