共通スクリプトにジョブの停止コマンドを記載していたのを各スクリプトに転記

diff --git a/web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/training_scripts.yaml b/web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/training_scripts.yaml
--- a/web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/training_scripts.yaml
+++ b/web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/training_scripts.yaml
@@ -8,7 +8,13 @@ data:
     bash /kqi/scripts/common/show-logo
     bash /kqi/scripts/common/prepare-kqi-conf
     bash /kqi/scripts/common/prepare-git
-    bash /kqi/scripts/common/prepare-dataset
+
+    echo "------------------------- [KAMONOHASHI Prepare] deploy dataset $DATASET_ID into /kqi/input . -------------------------"
+    kqi dataset download-files -d /kqi/input $DATASET_ID && kqi dataset get -d /kqi/input/meta.json $DATASET_ID
+    if [ $? -ne 0 ]; then
+        echo "dataset download-files failed"
+        kqi training halt $TRAINING_ID
+    fi
   main: |
     bash /kqi/scripts/common/wait-ready
     cd /kqi/git
